{
  description = "Self-rendering quine example using niccup";

  inputs = {
    niccup.url = "path:../..";
    nixpkgs.follows = "niccup/nixpkgs";
  };

  outputs = { self, nixpkgs, niccup }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f system);
    in {
      packages = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          h = niccup.lib;

          source = builtins.readFile ./flake.nix;

          page = h.renderPretty [
            "html" { lang = "en"; }
            [ "head"
              [ "meta" { charset = "utf-8"; } ]
              [ "title" "Quine" ]
              [ "style" (h.raw ''
                body { max-width: 800px; margin: 2rem auto; padding: 0 1rem; font-family: system-ui; background: #fafafa; }
                h1 { color: #333; }
                pre { background: #1a1a2e; color: #eee; padding: 1rem; border-radius: 8px; overflow-x: auto; }
                .meta { color: #666; font-style: italic; }
              '') ]
            ]
            [ "body"
              [ "h1" "This page was generated by:" ]
              [ "pre" [ "code" source ] ]
              [ "p.meta" "The above Nix code, when evaluated, produces this exact HTML." ]
            ]
          ];

          indexHtml = pkgs.writeText "index.html" page;

        in {
          default = pkgs.runCommand "quine" {} ''
            mkdir -p $out
            cp ${indexHtml} $out/index.html
          '';
        });
    };
}
